name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  ENV: ${{ vars.ENV }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build & Deploy
        run: |
          npm i -w=@sheriff-sale/config
          npm i -w=@sheriff-sale/database
          npm i -w=@sheriff-sale/backend
          npm i -w=@sheriff-sale/frontend
          npm run build
      - name: Database Migration
        run: |
          npm run db:migrate:deploy
          npm run db:push
      - name: Install AWS CLI
        run: |
          sudo apt-get -q install -y python3-pip
          pip3 install awscli
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_default_region $AWS_DEFAULT_REGION
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - name: Deploy AWS Stack
        run: |
          cd backend
          npx cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_DEFAULT_REGION}
          npx cdk deploy --require-approval never
